# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DashSensor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DashSensor
  pod 'ElasticSearchQuery', :git => 'https://github.com/Dekkoh/ElasticSearchQuery'
  pod 'Charts'

end

target 'DashSensorIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DashSensor
  pod 'ElasticSearchQuery', :git => 'https://github.com/Dekkoh/ElasticSearchQuery'
  pod 'Charts'

end