use_frameworks!

target 'ElasticSearchQuery_Example' do
  pod 'ElasticSearchQuery', :path => '../'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'

  target 'ElasticSearchQuery_Tests' do
    inherit! :search_paths

    
  end
end
